version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: product_crud
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Qwerty123$
    ports:
      - "5432:5432"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/product-crud
    ports:
      - "8000:8000"
    depends_on:
      - db
      - es
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
 
